import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const BACKSLASH_REGEX = /\\/g;
const TSX_EXT_REGEX = /\.tsx?$/;

export interface IconComponentGenerationOptions {
  outputFile: string;
  typesFileRelativePath: string;
  verbose?: boolean;
}

export function generateIconComponent(
  options: IconComponentGenerationOptions
): void {
  const { outputFile, typesFileRelativePath, verbose = true } = options;

  try {
    const projectRoot = process.cwd();
    const absoluteOutputFile = resolve(projectRoot, outputFile);

    const normalizedImportPath = typesFileRelativePath
      .replace(BACKSLASH_REGEX, "/")
      .replace(TSX_EXT_REGEX, "");

    const content = `// Auto-generated by typed-svg-sprite-astro
// Do not edit this file manually

import type { IconHref } from "${normalizedImportPath}";

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  /** The icon href (import from generated/icons.ts) */
  href: IconHref;
  /** Size shorthand for width and height */
  size?: number | string;
}

export function Icon({
  href,
  size = 24,
  width,
  height,
  className = "",
  viewBox = "0 0 24 24",
  fill = "currentColor",
  ...props
}: IconProps) {
  return (
    <svg
      className={className}
      width={width || size}
      height={height || size}
      viewBox={viewBox}
      fill={fill}
      aria-hidden="true"
      {...props}
    >
      <use href={href} />
    </svg>
  );
}
`;

    const outputDir = dirname(absoluteOutputFile);
    mkdirSync(outputDir, { recursive: true });
    writeFileSync(absoluteOutputFile, content, "utf8");

    if (verbose) {
      console.log(`[svg-sprite] Generated Icon component -> ${outputFile}`);
    }
  } catch (error) {
    if (verbose) {
      console.error("[svg-sprite] Error generating Icon component:", error);
    }
    throw error;
  }
}
