import fs from "node:fs";
import path from "node:path";
import type { SvgSymbol } from "./core.js";

export interface TypesGenerationOptions {
  symbols: SvgSymbol[];
  spriteUrl: string;
  spriteFilename: string;
  outputFile: string;
  verbose?: boolean;
}

export function generateTypesFile(options: TypesGenerationOptions): void {
  const {
    symbols,
    spriteUrl,
    spriteFilename,
    outputFile,
    verbose = true,
  } = options;

  try {
    const projectRoot = process.cwd();
    const absoluteOutputFile = path.resolve(projectRoot, outputFile);
    const spriteUrlWithFilename = spriteUrl.endsWith("/")
      ? `${spriteUrl}${spriteFilename}`
      : `${spriteUrl}/${spriteFilename}`;

    const enumEntries = symbols
      .map((s) => {
        const enumKey = s.originalId.replace(/-/g, "_").toUpperCase();
        return `  ${enumKey} = "${s.id}",`;
      })
      .join("\n");

    const iconExports = symbols
      .map((s) => {
        const constantName = s.originalId.replace(/-/g, "_").toUpperCase();
        return `export const ${constantName}: IconHref = "${spriteUrlWithFilename}#${s.id}";`;
      })
      .join("\n");

    const content = `// Auto-generated by typed-svg-sprite-astro
// Do not edit this file manually

/**
 * Available icon IDs in the sprite
 */
export enum IconId {
${enumEntries}
}

/**
 * Type-safe icon href (sprite URL + fragment identifier)
 */
export type IconHref = \`${spriteUrlWithFilename}#\${IconId}\`;

/**
 * Get the full sprite URL for an icon ID
 */
export function getIconHref(iconId: IconId): IconHref {
  return \`${spriteUrlWithFilename}#\${iconId}\` as IconHref;
}

/**
 * Pre-built icon references
 */
${iconExports}

/**
 * All available icons as an array
 */
export const allIcons: IconId[] = [
${symbols.map((s) => `  IconId.${s.originalId.replace(/-/g, "_").toUpperCase()},`).join("\n")}
];
`;

    const outputDir = path.dirname(absoluteOutputFile);
    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(absoluteOutputFile, content, "utf8");

    if (verbose) {
      console.log(`[svg-sprite] Generated types file -> ${outputFile}`);
    }
  } catch (error) {
    if (verbose) {
      console.error("[svg-sprite] Error generating types file:", error);
    }
    throw error;
  }
}
