import type { OrderDTO } from "@medusajs/framework/types";

/**
 * Mock order data for email template previews
 */
export const mockOrder = {
  id: "order_01K639QM8W1G6SR2BB876GZJ59",
  status: "pending",
  created_at: "2025-09-26T15:19:42.621Z",
  canceled_at: null,
  email: "customer@example.com",
  display_id: 885,
  custom_display_id: null,
  currency_code: "usd",
  metadata: null,
  total: 196.62,
  credit_line_total: 0,
  item_subtotal: 189.62,
  item_total: 189.62,
  item_tax_total: 0,
  original_item_tax_total: 0,
  item_discount_total: 0,
  shipping_subtotal: 7,
  original_total: 196.62,
  original_tax_total: 0,
  subtotal: 196.62,
  discount_total: 0,
  discount_subtotal: 0,
  shipping_total: 7,
  shipping_tax_total: 0,
  original_shipping_tax_total: 0,
  shipping_discount_total: 0,
  tax_total: 0,
  summary: {
    paid_total: 0,
    difference_sum: 0,
    raw_paid_total: { value: "0", precision: 20 },
    refunded_total: 0,
    transaction_total: 0,
    pending_difference: 196.62,
    raw_difference_sum: { value: "0", precision: 20 },
    raw_refunded_total: { value: "0", precision: 20 },
    current_order_total: 196.62,
    original_order_total: 196.62,
    raw_transaction_total: { value: "0", precision: 20 },
    raw_pending_difference: { value: "196.62", precision: 20 },
    raw_current_order_total: { value: "196.62", precision: 20 },
    raw_original_order_total: { value: "196.62", precision: 20 },
  },
  version: 1,
  region_id: "reg_01J9BARYJPG4N23XB9MDFASMNT",
  customer_id: "cus_01K639NK56K7QC1YHQDRTJZMKF",
  sales_channel_id: "sc_01J99451DMEJ0BYTMQ44NEQ8N0",
  items: [
    {
      id: "ordli_01K639QM8WKDKH0NN14J8ECV8Q",
      title: "8-Pack",
      subtitle: "Matcha Dream",
      thumbnail:
        "https://s3.eu-central-1.amazonaws.com/medusajs.cloud-data-prod-euc1-20241127132538579500000002/e13816f2b6122e01d87/product-10-01J9C5R48A408H9T28NT5S5NX7.png",
      variant_id: "variant_01J9RZETCBAZT6RCYD7D0EEPCC",
      product_id: "prod_01J9A51JXCGGCWQZYYACDZ2V0H",
      product_title: "Matcha Dream",
      product_description:
        "Delight in our Matcha Dream cookies, where the earthy taste of matcha meets sweet white chocolate chips.",
      product_subtitle: "A zen-like cookie experience",
      product_type: "Specialty Cookie",
      product_handle: "matcha-dream",
      variant_sku: "SKU-22",
      variant_title: "8-Pack",
      requires_shipping: true,
      is_giftcard: false,
      is_discountable: true,
      is_tax_inclusive: false,
      unit_price: 4.99,
      quantity: 1,
      subtotal: 4.99,
      total: 4.99,
      original_subtotal: 4.99,
      original_total: 4.99,
      discount_total: 0,
      tax_total: 0,
    },
    {
      id: "ordli_01K639QM8W34XC7T4KPJ6Y19TB",
      title: "8-Pack",
      subtitle: "Dark Chocolate Peanut Butter Chip",
      thumbnail:
        "https://s3.eu-central-1.amazonaws.com/medusajs.cloud-data-prod-euc1-20241127132538579500000002/e13816f2b6122e01d87/product-2-01J9C5C33HW0A7Z3FBP9VPD8SN.png",
      variant_id: "variant_01J9RY4RD0SCXHKMF0HE85WREF",
      product_id: "prod_01J9A2QYCBTAQT3XN27XDTH8EX",
      product_title: "Dark Chocolate Peanut Butter Chip",
      product_description:
        "Experience the bold flavors of dark chocolate paired with creamy peanut butter chips.",
      product_subtitle: "A sophisticated twist on a classic combo",
      product_type: "Gourmet Cookie",
      product_collection: "Nutty & Nice",
      product_handle: "dark-chocolate-peanut-butter-chip",
      variant_sku: "SKU-9",
      variant_title: "8-Pack",
      requires_shipping: true,
      is_giftcard: false,
      is_discountable: true,
      is_tax_inclusive: false,
      unit_price: 4.99,
      quantity: 3,
      subtotal: 14.97,
      total: 14.97,
      original_subtotal: 14.97,
      original_total: 14.97,
      discount_total: 0,
      tax_total: 0,
    },
  ],
  shipping_address: {
    id: "caaddr_01K639NK63P8JCBM86APZZ823V",
    customer_id: null,
    company: "Munchies Inc",
    first_name: "John",
    last_name: "Doe",
    address_1: "123 Cookie Street",
    address_2: "",
    city: "Sweet City",
    country_code: "us",
    province: "CA",
    postal_code: "12345",
    phone: null,
    metadata: null,
    created_at: "2025-09-26T15:18:35.971Z",
    updated_at: "2025-09-26T15:18:35.971Z",
    deleted_at: null,
  },
  billing_address: {
    id: "caaddr_01K639NK63P8JCBM86APZZ824V",
    customer_id: null,
    company: "Munchies Inc",
    first_name: "John",
    last_name: "Doe",
    address_1: "123 Cookie Street",
    address_2: "",
    city: "Sweet City",
    country_code: "us",
    province: "CA",
    postal_code: "12345",
    phone: null,
    metadata: null,
    created_at: "2025-09-26T15:18:35.971Z",
    updated_at: "2025-09-26T15:18:35.971Z",
    deleted_at: null,
  },
  shipping_methods: [
    {
      id: "ordsm_01K639QM8W3J96SMBN3EGMWE7H",
      name: "Express Shipping",
      description: null,
      is_tax_inclusive: false,
      shipping_option_id: "so_01JABKG19CB81NN1EZYVJ8N5FC",
      amount: 7,
      subtotal: 7,
      total: 7,
      original_subtotal: 7,
      original_total: 7,
      discount_total: 0,
      tax_total: 0,
    },
  ],
  fulfillments: [],
  payment_status: "authorized",
  fulfillment_status: "not_fulfilled",
} as unknown as OrderDTO;
